Add apostrophes to contractions
vblanco20-1/vulkan-guide pull request #33
Opened 2021-02-02 16:51 UTC by alexdmiller

I found the text very hard to read due to the lack of apostrophes to differentiate `it's` from `its`. This PR picks off the low hanging fruit via find-and-replace. [Here's](https://www.dummies.com/education/language-arts/grammar/how-to-use-apostrophes-to-form-contractions/) a guide to contractions in English which might be useful.

2021-02-02 17:04 UTC, cdgiessen requested changes
All but 2 places look okay to me.

2021-02-02 17:04 UTC, cdgiessen commented on docs/chapter-1/vulkan_renderpass_code.md
> +	color_attachment.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_don't_CARE;
If this is due to a search and replace gone wrong, then it needs to be corrected.
Even the Vulkan API gets it 'wrong' it seems. (Though I would not want to have to type grammatically correct English for what should be a programming API...)

2021-02-02 17:04 UTC, cdgiessen commented on docs/chapter-3/depth_buffer.md
> +    depth_attachment.stencilStoreOp = VK_ATTACHMENT_STORE_OP_don't_CARE;
Same as above.

2021-02-20 19:45 UTC, merged

2021-02-20 19:45 UTC, vblanco20-1 commented
All good, thanks for the help