Update Vulkan Overview
vblanco20-1/vulkan-guide pull request #6
Opened 2020-10-19 11:51 UTC by NixAJ

I propose the following changes (See Commits) to the Vulkan Overview page.

My main focus was to change the "tone" from more of a "conversation" to an "explanation", and to do some general rewording and restructuring of sentences.

Here is my current todo list
- [x] ## What is Vulkan?
- [x] ## When to use Vulkan
- [ ] ## Overview of Vulkan API
- [ ] ## Multiplatform 
- [ ] ## Validation layers 
- [ ] ## Usage and general mindset

If you have any feedback on this or would like to discuss my changes please comment.

2020-10-21 03:25 UTC, cdgiessen requested changes
I hope these comments don't come off as too contradictory, but I felt that there were a lot of small things that could be fixed to improve the clarity and flow of the text.

2020-10-21 03:25 UTC, cdgiessen commented on docs/introduction/vulkan_overview.md
> +It is important to note that the Validation Layers does not catch bugs like uninitialized memory and bad pointers. For bugs related to uninitialized memory and bad pointers
This repeats `uninitialized memory and bad pointers` in less than 10 words. It makes the text courser and harder to parse.

2020-10-21 03:25 UTC, cdgiessen commented on docs/introduction/vulkan_overview.md
> +The vulkan API is vast and as a result it is easy to make mistakes, but this is where Validation Layers comes to the rescue.
I do like the change of the initial description. The "fortunately ..." is clunky. But the change drops *what* the validation layers are, and immediately starts describing how they work (that they intercept functions).

2020-10-21 03:25 UTC, cdgiessen commented on docs/introduction/vulkan_overview.md
> +without seeing validation errors, you can reasonably assume that your application will work across a wide variety of hardware.
This drops the info about situations which may be drastically different between hardware. Saying that apps should always have a clean output is nice (as most devs want to eliminate all error/warning messages), but a new developer to vulkan wouldn't know what all could be different between hardware.

2020-10-21 03:25 UTC, cdgiessen commented on docs/introduction/vulkan_overview.md
> +code being ran through Vulkan and validate that it is correct and then perform the call to the driver, this also means you will have reduced
I do like the addition of how performance is impacted when running validation, but it should be noted why its slower. (though, fixing the previous comment I made about gateways would likely fix this one...)

2020-10-21 03:32 UTC, cdgiessen commented
I will add that there were many changes I approve of. Re-reading the original text I found quite a few things that weren't very clean or clear which your changes improved upon.

2020-10-21 13:52 UTC, NixAJ commented on docs/introduction/vulkan_overview.md
> +The Vulkan API is a standard for developers to implement in their preferred environment.
The previous text said the following "and the API is a standard that anyone can implement", my intent behind my sentence was to improve clarity, any developer can take the Vulkan API and implement it in their preferred environment, where environment is referring to a multitude of factors such as "Device, Platform & Language"

2020-10-21 13:53 UTC, NixAJ commented on docs/introduction/vulkan_overview.md
> +The API is based on the C Syntax, and should be compatible with a vast majority of languages.
[12:39 PM] Nix: I assume the API is actually written in C and not "based on"
[12:39 PM] vblanco: not really written in C

This is my reasoning for what I wrote, I can reword it.

2020-10-21 14:25 UTC, NixAJ commented on docs/introduction/vulkan_overview.md
> +Validation Layers operate as a gateway between your function call and the graphics driver, this allows the Validation Layer to intercept all
I agree, I'll reword it, I wasn't entirely use on the use of "Gateway" initially

2020-10-21 14:59 UTC, NixAJ commented
@cdgiessen Thank you so much for your feedback, please take another look through the changes when you have time

2020-10-22 17:31 UTC, merged

2020-10-22 17:51 UTC, cdgiessen commented
Only now read the changes after the fact, they look great. Thanks!